### ISSUE TITLE
Request for Sample Data

### ISSUE THREAD

**Issue by gxy-gxy** [WowCZ/LongMIT#1]
Hello,

I hope this message finds you well. I would greatly appreciate it if you could provide me with a few sample data entries.

Thank you for your assistance!

Best regards,

**Comment by WowCZ** [comment]
Thanks for your kind advise. I have upload the toy samples in _assets/example_datasets_, which is partial sampled from our  used text corpus. I also update the README, which introduced the format of specific sample entries in different synthesis processes.

**Comment by gxy-gxy** [comment]
It seems that there are no example datasets available in the assets/ directory?

**Comment by WowCZ** [comment]
Sorry, I forget to change the gitignore. You can get now.
