### ISSUE TITLE
3hop, 4hop question merging prompt

### ISSUE THREAD

**Issue by kai-wen-yang** [WowCZ/LongMIT#4]
Can you please provide 3hop, 4hop question merging prompt?

**Comment by WowCZ** [comment]
The merging prompt is always as shown in A.2.5 (our first released Aixiv version). The 3-hop qa pair is merged by one synthetic 2-hop qa pair and related single-doc qa pair. In other words, the n-hop qa pairs is merged by one synthetic (n-1)-hop qa pair and related single-doc qa pair.
