### ISSUE TITLE
All the 'language' columns are 'en'

### ISSUE THREAD

**Issue by kai-wen-yang** [WowCZ/LongMIT#5]
<img width="1756" alt="截屏2024-10-12 17 06 09" src="https://github.com/user-attachments/assets/8e3399df-c01d-4d95-90a8-e78f7054b3c3">

**Comment by WowCZ** [comment]
Thanks for your reminding. I will upload the updated dataset with the corrrect language and type soon.

**Comment by WowCZ** [comment]
We have updated the language and type in the datasets.
