### ISSUE TITLE
Evaluating performance on short-context benchmarks

### ISSUE THREAD

**Issue by lilakk** [WowCZ/LongMIT#6]
Hi all, I noticed the paper doesn't address how finetuning on LongMIT might impact performance on short-context tasks. I understand this is still a work in progress, but do you have plans to explore the trade-off between long and short-context performance in the near future?

**Comment by WowCZ** [comment]
It is a good question. However, in this work, we only focus on proposing a framework to synthetise the high-quality long-context datasets. As I know, there are some studies that found the long-context corpus has destructive effects for short-term dependency tasks, like math and code. In our synthetic datasets, we also guarante that the evidence documents distribute unifromally. It means that there are some samples, whose evidence documents are put on the last of the long context. In somehow, the short-context dependency situation is also simulated. To constructed a comprehensive LLM, we will explore the effects beween long and short-context performance in different experiment settings. If you have interests, we can delve into this research topic together. We will update the related experiments under this issue.
